---
title: Topics in Mathematical Statistics Note
author: Huei-Yuan Yao
date: '2022-09-27'
slug: []
categories: []
tags: []
description: ''
topics: []
---
This post is to record my deployment of [my notes in topics in mathematical statistics](https://huei-yuan-yao.github.io/Topics-in-Math-Stat_note/). This note is built on [Rbookdown](https://bookdown.org/yihui/bookdown/), I am really appreciated all of the contributors to this package. This package and [Rblogdown](https://bookdown.org/yihui/blogdown/) are both amazing and truly friendly to anyone who does not familiar with designing website like html, css, javascript just like me. The most appealing part (at least for me) is they incorporate the R markdown which is awesome for showing some data analysis work. Thanks to those, I can just focus on writing in R studio now. 

This note is still under writing now, anyone noticing the book is very welcome to discuss the content which I believe there may exist a lot of typos. The lecture "Topics in Mathematical Statistics" is a phD course I took in NCCU (National Chengchi University) based on the textbook written by Jun Shao. Here I'd like to leave the further introduction in the note. 


